#!/usr/bin/env bash
# install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sed -i '/a add_header X-Served-By "$HOSTNAME";'
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
