#!/usr/bin/env bash
# install HAproxi
sudo apt -y update
sudo apt install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_original
sudo sed -i "$ a frontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 2852-web-01 34.138.145.79:80 check\n\tserver 2852-web-02 18.207.128.190:80 check" /etc/haproxy/haproxy.cfg
sudo cp /etc/default/haproxy /etc/default/haproxy_original
sudo sed -i "$ a ENABLED=1" /etc/default/haproxy
sudo service haproxy start
