#!/usr/bin/env bash
# Process and PID file
echo $BASHPID > /var/run/holbertonscript.pid
i=1
while ((i))
do
    echo "To infinity and beyond"
    sleep 2
    trap 'I hate the kill command && sudo rm /var/run/holbertonscript.pid' SIGTERM
    trap 'Y U no love me?!' SIGINT
done
