#!/usr/bin/env bash
# Displays Holberton School 10 times.
i=0
while ((i<10))
do
    if [ $i = 3 ]
    then
        echo "bad luck"
    elif [ $i = 7 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((i++))
done
