#!/usr/bin/env bash
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/copy.cpy
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/copy.cpy
echo "8.8.8.8 facebook.com" >> ~/copy.cpy
cp -f ~/copy.cpy /etc/hosts
